#!/bin/sh

# Generate a krb5.conf file in the current directory for testing purposes.
# Takes one command-line argument: the default realm to use.  Strips out the
# entire [appdefaults] section to avoid picking up any local configuration and
# sets the default realm as indicated.
#
# Written by Russ Allbery <rra@stanford.edu>
# Copyright 2006, 2007, 2008, 2010, 2011
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

set -e

# Load the test library.
. "$SOURCE/tap/libtap.sh"
cd "$BUILD"

# If there is no default realm specified on the command line, we leave the
# realm information alone.
realm="$1"

# Locate the krb5.conf file to use as a base.  Prefer the one in the test
# configuration area, if it exists.
krb5conf=`test_file_path config/krb5.conf`
if [ -z "$krb5conf" ] ; then
    for p in /etc/krb5.conf /usr/local/etc/krb5.conf ; do
        if [ -r "$p" ] ; then
            krb5conf="$p"
            break
        fi
    done
fi
if [ -z "$krb5conf" ] ; then
    echo 'no krb5.conf found, see test instructions' >&2
    exit 1
fi

# We found a krb5.conf file.  Generate our munged one.
awk '
    BEGIN                             { skip = 0 }
    /^ *\[appdefaults\]/              { skip = 1 }
    !/^ *\[appdefaults\]/ && / *\[/   { skip = 0 }

    { if (skip == 0) print }
' "$p" > krb5.conf.tmp
if [ -n "$realm" ] ; then
    sed -e "s/\\(default_realm.*=\\) .*/\\1 $realm/" \
        krb5.conf.tmp > krb5.conf
    rm krb5.conf.tmp
else
    mv krb5.conf.tmp krb5.conf
fi
